spring:
  application:
    name: jackal-speech

speech:
  service: "${SPEECH_SERVICE:tencent}"
  tencent:
    keyId: "${TENCENT_KEY:123456}"
    keySecret: "${TENCENT_SECRET:123456}"
  baidu:
    appId: "${BAIDU_APPID:123456}"
    apiKey: "${BAIDU_KEY:123456}"
    secretKey: "${BAIDU_SECRET:123456}"
  microsoft:
    key: "${MICROSOFT_KEY:123456}"
    region: "${MICROSOFT_REGION:eastasia}"
  aliyun:
    appKey: "${ALIYUN_APPKEY:123456}"
    accessKeyId: "${ALIYUN_KEYID:123456}"
    accessKeySecret: "${ALIYUN_KEYSECRET:123456}"
    url: "https://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/asr"
