spring:
  application:
    name: jackal-springboot-speech

speech:
  service: "${SPEECH_SERVICE:tencent}"
  tencent:
    keyId: "${TENCENT_KEY:123456}"
    keySecret: "${TENCENT_SECRET:123456}"
  baidu:
    appId: "${BAIDU_APPID:123456}"
    apiKey: "${BAIDU_KEY:123456}"
    secretKey: "${BAIDU_SECRET:123456}"
  microsoft:
    key: "${MICROSOFT_KEY:123456}"
    region: "${MICROSOFT_REGION:eastasia}"
  xunfei:
    appId: "${XUNFEI_APPID:123456}"
    apiKey: "${XUNFEI_APIKEY:123456}"
    apiSecret: "${XUNFEI_APISECRET:123456}"
    vcn: "aisbabyxu"

